import "reflect-metadata";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { NestFactory } from "@nestjs/core";
import { FastifyAdapter, type NestFastifyApplication } from "@nestjs/platform-fastify";
import type { OpenAPIObject, OperationObject, PathItemObject } from "@nestjs/swagger";
import { AppModule } from "./app.module.js";
import { createMarketplaceOpenApiDocument } from "./openapi.js";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(dirname, "../../..");
const openApiOutput = path.join(workspaceRoot, "documentation/api/openapi.json");
const routeRegistryOutput = path.join(workspaceRoot, "packages/api-client/src/generated/routes.ts");

const httpMethods = ["get", "post", "put", "patch", "delete", "options", "head", "trace"] as const;

type HttpMethod = Uppercase<(typeof httpMethods)[number]>;
type ContractRoute = { method: HttpMethod; path: string; operationId: string };

function isOperation(value: unknown): value is OperationObject {
  return Boolean(value && typeof value === "object" && ("responses" in value || "operationId" in value));
}

function normaliseOperationId(method: string, routePath: string, operation: OperationObject): string {
  if (operation.operationId) return operation.operationId;
  return `${method}_${routePath}`
    .replaceAll(/[{}]/g, "")
    .replaceAll(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function collectRoutes(document: OpenAPIObject): ContractRoute[] {
  return Object.entries(document.paths)
    .flatMap(([routePath, pathItem]) =>
      httpMethods.flatMap((method) => {
        const operation = (pathItem as PathItemObject | undefined)?.[method];
        if (!isOperation(operation)) return [];
        return [{
          method: method.toUpperCase() as HttpMethod,
          path: routePath,
          operationId: normaliseOperationId(method, routePath, operation),
        }];
      }),
    )
    .sort((left, right) => left.path.localeCompare(right.path) || left.method.localeCompare(right.method));
}

function routeRegistrySource(routes: ContractRoute[]): string {
  return `/* This file is generated by pnpm openapi:generate. Do not edit by hand. */
export const commerceApiRoutes = ${JSON.stringify(routes, null, 2)} as const;

export type CommerceApiRoute = (typeof commerceApiRoutes)[number];
export type CommerceApiRouteMethod = CommerceApiRoute["method"];
export type CommerceApiRoutePath = CommerceApiRoute["path"];
`;
}

async function main(): Promise<void> {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter({ logger: false }), {
    logger: false,
    rawBody: true,
  });
  await app.init();

  try {
    const document = createMarketplaceOpenApiDocument(app);
    const routes = collectRoutes(document);

    await mkdir(path.dirname(openApiOutput), { recursive: true });
    await mkdir(path.dirname(routeRegistryOutput), { recursive: true });
    await writeFile(openApiOutput, `${JSON.stringify(document, null, 2)}\n`);
    await writeFile(routeRegistryOutput, routeRegistrySource(routes));
  } finally {
    await app.close();
  }
}

await main();
