import type { Metadata } from "next";
import { BookOpenCheck, KeyRound, ShieldCheck } from "lucide-react";
import { LoginForm } from "@/components/login-form";

export const metadata: Metadata = { title: "Administrator sign in" };

export default function LoginPage() {
  return <main className="grid min-h-screen bg-white lg:grid-cols-[minmax(20rem,.8fr)_minmax(28rem,1.2fr)]"><aside className="hidden flex-col justify-between bg-[#18201e] p-10 text-white lg:flex xl:p-14"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-sky-300 text-blue-950"><ShieldCheck className="h-5 w-5" /></span><div><div className="text-base font-extrabold">NISTER</div><div className="text-xs text-slate-400">Marketplace control</div></div></div><div className="max-w-md"><p className="text-3xl font-bold leading-tight">Operational control with accountable decisions.</p><div className="mt-8 grid gap-4 text-sm text-slate-300"><div className="flex gap-3"><BookOpenCheck className="mt-0.5 h-5 w-5 shrink-0 text-sky-300" /><span>Financial views are derived from immutable posted ledger transactions.</span></div><div className="flex gap-3"><KeyRound className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" /><span>Sensitive actions require role permission, reason, and evidence.</span></div><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><span>Every command carries request, actor, and idempotency context.</span></div></div></div><p className="text-xs text-slate-500">Authorised NISTER personnel only</p></aside><section className="grid place-items-center p-5 sm:p-10"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3 lg:hidden"><span className="grid h-9 w-9 place-items-center rounded-md bg-navy text-white"><ShieldCheck className="h-5 w-5" /></span><div className="font-extrabold">NISTER <span className="font-medium text-slate-500">Admin</span></div></div><p className="text-xs font-bold uppercase text-navy">Restricted access</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Sign in to marketplace control</h1><p className="mt-2 text-sm leading-6 text-slate-500">Use your administrator identity. MFA may be required.</p><LoginForm /><div className="mt-6 flex gap-2 border-t border-line pt-5 text-xs leading-5 text-slate-500"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" />Authentication attempts are security logged and monitored.</div></div></section></main>;
}
