import { Check, Play, RotateCcw, ShieldBan, UserRoundCog } from "lucide-react";
import type { VendorReview } from "@/lib/types";
import { ActionDialog } from "./action-dialog";

export function VendorActions({ vendor }: { vendor: VendorReview }) {
  const endpoint = `/admin/vendors/${vendor.id}/actions`;
  if (vendor.status === "SUBMITTED") return <ActionDialog endpoint={endpoint} action="BEGIN_REVIEW" title={`Begin review of ${vendor.name}?`} description="Assign this application to your review queue and lock the current submitted version." confirmLabel="Begin review" trigger={<span className="btn-secondary h-8 px-2.5 text-xs"><Play className="h-3.5 w-3.5" />Review</span>} />;
  if (vendor.status === "UNDER_REVIEW") return <div className="flex justify-end gap-1.5"><ActionDialog endpoint={endpoint} action="REQUEST_INFORMATION" title={`Request information from ${vendor.name}?`} description="The application will return to the vendor with your reason and supporting policy reference." confirmLabel="Request information" requireReason requireEvidence trigger={<span className="inline-grid h-8 w-8 place-items-center rounded-md border border-slate-300 text-slate-600 hover:bg-slate-50" title="Request information"><UserRoundCog className="h-4 w-4" /></span>} /><ActionDialog endpoint={endpoint} action="APPROVE" title={`Approve ${vendor.name}?`} description="Confirm that identity, business, payout, and fulfilment checks are complete against the submitted evidence." confirmLabel="Approve vendor" requireEvidence trigger={<span className="inline-grid h-8 w-8 place-items-center rounded-md bg-navy text-white hover:bg-blue-950" title="Approve vendor"><Check className="h-4 w-4" /></span>} /></div>;
  if (vendor.status === "APPROVED") return <ActionDialog endpoint={endpoint} action="SUSPEND" title={`Suspend ${vendor.name}?`} description="New listings and orders will be blocked. Existing obligations remain visible for operational resolution." confirmLabel="Suspend vendor" requireReason requireEvidence tone="danger" trigger={<span className="btn-secondary h-8 px-2.5 text-xs text-red-700"><ShieldBan className="h-3.5 w-3.5" />Suspend</span>} />;
  if (vendor.status === "SUSPENDED") return <ActionDialog endpoint={endpoint} action="RESTORE" title={`Restore ${vendor.name}?`} description="Restore marketplace access only after the suspension issue has been fully resolved." confirmLabel="Restore vendor" requireReason requireEvidence trigger={<span className="btn-secondary h-8 px-2.5 text-xs"><RotateCcw className="h-3.5 w-3.5" />Restore</span>} />;
  return <span className="text-xs text-slate-400">Awaiting vendor</span>;
}
