import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Banknote, Check, Clock3, MapPin, Package, Route, X } from "lucide-react-native";
import { Alert, StyleSheet, Text, View } from "react-native";

import { Button, Card, Divider, PageHeader, QueryState, Screen, StatusBadge } from "@/components/ui";
import { driverData } from "@/data";
import { formatMoney, formatTime, newIdempotencyKey } from "@/lib/format";
import { colors, spacing } from "@/theme";

export default function OfferScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const queryClient = useQueryClient();
  const offer = useQuery({ queryKey: ["driver-offer", id], queryFn: () => driverData.getOffer(id), enabled: Boolean(id), refetchInterval: 10_000 });
  const accept = useMutation({ mutationFn: () => driverData.acceptOffer({ offerId: offer.data!.id, expectedOfferVersion: offer.data!.version, idempotencyKey: newIdempotencyKey("offer-accept") }), onSuccess: (delivery) => { void queryClient.invalidateQueries({ queryKey: ["driver-offers"] }); void queryClient.invalidateQueries({ queryKey: ["driver-home"] }); router.replace({ pathname: "/delivery/[id]", params: { id: delivery.id } }); } });
  const reject = useMutation({ mutationFn: () => driverData.rejectOffer({ offerId: offer.data!.id, expectedOfferVersion: offer.data!.version, idempotencyKey: newIdempotencyKey("offer-reject") }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["driver-offers"] }); router.back(); } });
  if (!offer.data) return <Screen><QueryState loading={offer.isLoading} error={offer.error} onRetry={() => void offer.refetch()} /></Screen>;
  const value = offer.data;
  return <Screen><PageHeader title="Delivery offer" subtitle={`Available until ${formatTime(value.expiresAt)}`} /><StatusBadge label="Full customer address hidden until acceptance" tone="info" /><Card><View style={styles.stop}><View style={styles.pin}><MapPin color={colors.primary} size={19} /></View><View style={styles.grow}><Text style={styles.label}>PICKUP AREA</Text><Text style={styles.value}>{value.pickupArea}</Text></View></View><Divider /><View style={styles.stop}><View style={styles.pin}><MapPin color={colors.danger} size={19} /></View><View style={styles.grow}><Text style={styles.label}>DROP-OFF AREA</Text><Text style={styles.value}>{value.dropoffArea}</Text></View></View></Card><View style={styles.grid}><Metric icon={Route} label="Distance" value={`${value.estimatedDistanceKm.toFixed(1)} km`} /><Metric icon={Clock3} label="Duration" value={`About ${value.estimatedDurationMinutes} min`} /><Metric icon={Package} label="Packages" value={value.packageSize} /><Metric icon={Banknote} label="Earnings" value={formatMoney(value.expectedEarnings)} /></View>{value.cashOnDelivery ? <Card style={styles.cash}><Banknote color={colors.danger} size={22} /><View style={styles.grow}><Text style={styles.cashTitle}>Cash collection required</Text><Text style={styles.cashValue}>{formatMoney(value.cashOnDelivery)}</Text><Text style={styles.meta}>This amount is added to your cash liability only after verified completion.</Text></View></Card> : null}<Card><Text style={styles.meta}>{value.pickupCount} pickup{value.pickupCount === 1 ? "" : "s"} · {value.dropoffCount} drop-off{value.dropoffCount === 1 ? "" : "s"} · {value.vehicleRequirement}</Text></Card>{accept.error || reject.error ? <Text accessibilityRole="alert" style={styles.error}>The offer expired, changed, or was accepted elsewhere. Return to refresh offers.</Text> : null}<Button label="Accept delivery" icon={Check} loading={accept.isPending} disabled={reject.isPending} onPress={() => Alert.alert("Accept delivery?", "Only one driver can win this offer. The assignment is confirmed by the backend.", [{ text: "Cancel", style: "cancel" }, { text: "Accept", onPress: () => accept.mutate() }])} /><Button label="Reject offer" icon={X} variant="secondary" loading={reject.isPending} disabled={accept.isPending} onPress={() => reject.mutate()} /></Screen>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Route; label: string; value: string }) { return <Card style={styles.metric}><Icon color={colors.primary} size={20} /><Text style={styles.label}>{label}</Text><Text style={styles.metricValue} numberOfLines={2}>{value}</Text></Card>; }
const styles = StyleSheet.create({ stop: { flexDirection: "row", alignItems: "center", gap: spacing.md }, pin: { width: 38, height: 38, borderRadius: 6, backgroundColor: colors.background, alignItems: "center", justifyContent: "center" }, grow: { flex: 1, gap: 3 }, label: { color: colors.muted, fontSize: 10, fontWeight: "700" }, value: { color: colors.text, fontSize: 16, fontWeight: "800" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { width: "48%", minHeight: 108 }, metricValue: { color: colors.text, fontSize: 15, fontWeight: "700" }, cash: { flexDirection: "row", borderColor: colors.danger }, cashTitle: { color: colors.danger, fontSize: 14, fontWeight: "700" }, cashValue: { color: colors.text, fontSize: 20, fontWeight: "800" }, meta: { color: colors.muted, fontSize: 12, lineHeight: 18 }, error: { color: colors.danger, fontSize: 13, lineHeight: 18 } });
