import { useRouter } from "expo-router";
import { ChevronRight, FileText, LogOut, MapPinned, ShieldCheck, UserRound, Wrench } from "lucide-react-native";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { Button, Card, PageHeader, Screen, StatusBadge } from "@/components/ui";
import { useSessionStore } from "@/lib/session-store";
import { colors, spacing } from "@/theme";

const rows = [{ icon: UserRound, title: "Profile", detail: "Personal and emergency contact information" }, { icon: Wrench, title: "Vehicle", detail: "Motorbike · documents reviewed" }, { icon: FileText, title: "Documents", detail: "Identity, licence, insurance, and inspection" }, { icon: MapPinned, title: "Location settings", detail: "Foreground and active-shift permissions" }, { icon: ShieldCheck, title: "Security and devices", detail: "MFA, active devices, and privacy" }];
export default function AccountScreen() {
  const router = useRouter(); const session = useSessionStore((state) => state.session); const signOut = useSessionStore((state) => state.signOut);
  return <Screen><PageHeader title="Account" subtitle="Driver identity, vehicle, documents, and security." /><Card><View style={styles.profile}><View style={styles.avatar}><UserRound color={colors.primary} size={25} /></View><View style={styles.grow}><Text style={styles.name}>{session?.displayName ?? "Driver"}</Text><Text style={styles.meta}>{session?.email}</Text></View><StatusBadge label="Active" tone="success" /></View></Card>{rows.map(({ icon: Icon, title, detail }) => <View key={title} style={[styles.row, styles.disabled]}><Icon color={colors.muted} size={20} /><View style={styles.grow}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.meta}>{detail}</Text></View><StatusBadge label="Pending API" /></View>)}<Pressable accessibilityRole="button" accessibilityLabel="Review app permissions" onPress={() => router.push("/permissions")} style={({ pressed }) => [styles.row, pressed ? styles.pressed : null]}><MapPinned color={colors.primary} size={20} /><View style={styles.grow}><Text style={styles.rowTitle}>Review app permissions</Text><Text style={styles.meta}>Location and camera access</Text></View><ChevronRight color={colors.muted} size={20} /></Pressable><Button label="Sign out" icon={LogOut} variant="danger" onPress={() => { signOut(); router.replace("/sign-in"); }} /></Screen>;
}
const styles = StyleSheet.create({ profile: { flexDirection: "row", alignItems: "center", gap: spacing.md }, avatar: { width: 48, height: 48, borderRadius: 8, backgroundColor: colors.successSoft, alignItems: "center", justifyContent: "center" }, grow: { flex: 1, gap: 3 }, name: { color: colors.text, fontSize: 16, fontWeight: "800" }, meta: { color: colors.muted, fontSize: 12, lineHeight: 18 }, row: { minHeight: 66, borderWidth: 1, borderColor: colors.border, borderRadius: 6, backgroundColor: colors.surface, padding: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.md }, rowTitle: { color: colors.text, fontSize: 15, fontWeight: "700" }, disabled: { opacity: 0.72 }, pressed: { opacity: 0.68 } });
