import { useQuery } from "@tanstack/react-query";
import { Banknote, Landmark, WalletCards } from "lucide-react-native";
import { StyleSheet, Text, View } from "react-native";

import { Card, PageHeader, QueryState, Screen, SectionHeader, StatusBadge } from "@/components/ui";
import { driverData } from "@/data";
import { formatMoney, formatTime } from "@/lib/format";
import { colors, spacing } from "@/theme";

export default function EarningsScreen() {
  const earnings = useQuery({ queryKey: ["driver-earnings"], queryFn: driverData.earnings });
  return <Screen><PageHeader title="Earnings" subtitle="Delivery earnings, payouts, adjustments, and cash position." /><QueryState loading={earnings.isLoading} error={earnings.error} onRetry={() => void earnings.refetch()} />{earnings.data ? <><View style={styles.metrics}><Metric icon={WalletCards} label="Today" value={formatMoney(earnings.data.today)} /><Metric icon={Landmark} label="Available" value={formatMoney(earnings.data.available)} /></View><View style={styles.metrics}><Metric icon={Banknote} label="Pending" value={formatMoney(earnings.data.pending)} /><Metric icon={Banknote} label="Cash liability" value={formatMoney(earnings.data.cashLiability)} danger /></View><Card><Row label="This week" value={formatMoney(earnings.data.thisWeek)} /><Row label="Paid" value={formatMoney(earnings.data.paid)} /><Row label="Bonuses" value={formatMoney(earnings.data.bonuses)} /><Row label="Adjustments" value={formatMoney(earnings.data.adjustments)} /></Card><View style={styles.section}><SectionHeader title="Transactions" />{earnings.data.transactions.map((transaction) => <Card key={transaction.id}><View style={styles.row}><View style={styles.grow}><Text style={styles.strong}>{transaction.reference}</Text><Text style={styles.meta}>{transaction.kind} · {formatTime(transaction.occurredAt)}</Text></View><View style={styles.right}><Text style={styles.strong}>{formatMoney(transaction.amount)}</Text><StatusBadge label={transaction.status} tone={transaction.status === "PAID" || transaction.status === "EARNED" ? "success" : "neutral"} /></View></View></Card>)}</View></> : null}</Screen>;
}
function Metric({ icon: Icon, label, value, danger = false }: { icon: typeof Banknote; label: string; value: string; danger?: boolean }) { return <Card style={styles.metric}><Icon color={danger ? colors.danger : colors.primary} size={21} /><Text style={styles.meta}>{label}</Text><Text style={[styles.amount, danger ? styles.danger : null]} numberOfLines={1} adjustsFontSizeToFit>{value}</Text></Card>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.rowBetween}><Text style={styles.meta}>{label}</Text><Text style={styles.strong}>{value}</Text></View>; }
const styles = StyleSheet.create({ metrics: { flexDirection: "row", gap: spacing.sm }, metric: { flex: 1, minHeight: 115 }, amount: { color: colors.text, fontSize: 18, fontWeight: "800" }, danger: { color: colors.danger }, meta: { color: colors.muted, fontSize: 12, lineHeight: 18 }, rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md }, strong: { color: colors.text, fontSize: 14, fontWeight: "700" }, section: { gap: spacing.sm }, row: { flexDirection: "row", alignItems: "center", gap: spacing.md }, grow: { flex: 1, gap: 3 }, right: { alignItems: "flex-end", gap: spacing.xs } });
