import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { AlertTriangle, ArrowRight, Banknote, Bike, Power, ShieldAlert } from "lucide-react-native";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";

import { Button, Card, PageHeader, QueryState, SectionHeader, StatusBadge } from "@/components/ui";
import { dataMode, driverData } from "@/data";
import { formatMoney } from "@/lib/format";
import { useOfflineQueue } from "@/lib/offline-queue";
import { colors, spacing } from "@/theme";

export default function DriverHomeScreen() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const pending = useOfflineQueue((state) => state.events.filter((event) => event.status !== "SYNCING").length);
  const home = useQuery({ queryKey: ["driver-home"], queryFn: driverData.home, refetchInterval: 30_000 });
  const offers = useQuery({ queryKey: ["driver-offers"], queryFn: driverData.listOffers, enabled: home.data?.onlineStatus === "ONLINE", refetchInterval: 20_000 });
  const toggle = useMutation({ mutationFn: driverData.setOnline, onSuccess: (value) => { queryClient.setQueryData(["driver-home"], value); void queryClient.invalidateQueries({ queryKey: ["driver-offers"] }); } });
  return <View style={styles.screen}><PageHeader title="Driver home" subtitle={home.data ? `${home.data.currentZone} · ${home.data.currentVehicle}` : "Shift and delivery status"} action={dataMode === "demo" ? <StatusBadge label="Demo" tone="warning" /> : undefined} />
    <QueryState loading={home.isLoading} error={home.error} onRetry={() => void home.refetch()} />
    {home.data ? <>
      <Card style={styles.onlineCard}><View style={styles.onlineRow}><View style={styles.power}><Power color={home.data.onlineStatus === "ONLINE" ? colors.primary : colors.muted} size={24} /></View><View style={styles.grow}><Text style={styles.onlineTitle}>{home.data.onlineStatus === "ONLINE" ? "Online for offers" : "Offline"}</Text><Text style={styles.meta}>{home.data.onlineStatus === "ONLINE" ? "New delivery offers can arrive." : "Start a shift when you are ready."}</Text></View><Switch accessibilityLabel="Driver availability" value={home.data.onlineStatus === "ONLINE"} disabled={toggle.isPending || home.data.eligibilityBlocks.length > 0 || Boolean(home.data.activeDeliveryId)} onValueChange={(value) => toggle.mutate(value)} trackColor={{ false: colors.border, true: colors.successSoft }} thumbColor={home.data.onlineStatus === "ONLINE" ? colors.primary : colors.muted} /></View>
        {home.data.eligibilityBlocks.map((block) => <View key={block} style={styles.block}><AlertTriangle color={colors.danger} size={17} /><Text style={styles.blockText}>{block}</Text></View>)}
      </Card>
      {home.data.activeDeliveryId ? <Pressable accessibilityRole="button" accessibilityLabel="Open active delivery" onPress={() => router.push({ pathname: "/delivery/[id]", params: { id: home.data!.activeDeliveryId! } })} style={({ pressed }) => [styles.active, pressed ? styles.pressed : null]}><Bike color={colors.surface} size={24} /><View style={styles.grow}><Text style={styles.activeTitle}>Resume active delivery</Text><Text style={styles.activeMeta}>The delivery remains available after app restart.</Text></View><ArrowRight color={colors.surface} size={21} /></Pressable> : null}
      <View style={styles.metrics}><Card style={styles.metric}><Text style={styles.metricLabel}>Today</Text><Text style={styles.metricValue}>{formatMoney(home.data.todayEarnings)}</Text><Text style={styles.meta}>{home.data.todayDeliveries} deliveries</Text></Card><Card style={styles.metric}><Text style={styles.metricLabel}>Cash liability</Text><Text style={[styles.metricValue, Number(home.data.cashLiability.amountMinor) > 0 ? styles.cash : null]}>{formatMoney(home.data.cashLiability)}</Text><Text style={styles.meta}>Deposit outstanding cash promptly</Text></Card></View>
      {pending > 0 ? <Pressable accessibilityRole="button" accessibilityLabel={`${pending} pending sync events`} onPress={() => router.push("/sync-queue")} style={styles.sync}><ShieldAlert color={colors.info} size={19} /><Text style={styles.syncText}>{pending} offline event{pending === 1 ? "" : "s"} need attention</Text><ArrowRight color={colors.info} size={18} /></Pressable> : null}
      <View style={styles.section}><SectionHeader title="Delivery offers" />{home.data.onlineStatus !== "ONLINE" ? <Card><Text style={styles.meta}>Go online to receive eligible offers.</Text></Card> : <QueryState loading={offers.isLoading} error={offers.error} empty={offers.data?.length === 0} emptyLabel="No offers are available right now." onRetry={() => void offers.refetch()} />}{offers.data?.map((offer) => <Pressable key={offer.id} accessibilityRole="button" accessibilityLabel={`Offer from ${offer.pickupArea} to ${offer.dropoffArea}`} onPress={() => router.push({ pathname: "/offer/[id]", params: { id: offer.id } })} style={({ pressed }) => [styles.offer, pressed ? styles.pressed : null]}><View style={styles.route}><View><Text style={styles.routeLabel}>PICKUP</Text><Text style={styles.routeValue}>{offer.pickupArea}</Text></View><ArrowRight color={colors.muted} size={18} /><View style={styles.grow}><Text style={styles.routeLabel}>DROP-OFF</Text><Text style={styles.routeValue}>{offer.dropoffArea}</Text></View><Text style={styles.earning}>{formatMoney(offer.expectedEarnings)}</Text></View><Text style={styles.meta}>{offer.estimatedDistanceKm.toFixed(1)} km · about {offer.estimatedDurationMinutes} min · {offer.packageSize}</Text>{offer.cashOnDelivery ? <View style={styles.cashRow}><Banknote color={colors.danger} size={16} /><Text style={styles.cashText}>Collect {formatMoney(offer.cashOnDelivery)}</Text></View> : null}</Pressable>)}</View>
      <Button label="Emergency and safety" icon={ShieldAlert} variant="danger" onPress={() => router.push("/emergency")} />
    </> : null}
  </View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background, padding: spacing.lg, gap: spacing.lg }, onlineCard: { gap: spacing.md }, onlineRow: { flexDirection: "row", alignItems: "center", gap: spacing.md }, power: { width: 46, height: 46, borderRadius: 8, backgroundColor: colors.background, alignItems: "center", justifyContent: "center" }, grow: { flex: 1, gap: 3 }, onlineTitle: { color: colors.text, fontSize: 16, fontWeight: "800" }, meta: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  block: { flexDirection: "row", gap: spacing.sm, padding: spacing.sm, backgroundColor: colors.dangerSoft, borderRadius: 6 }, blockText: { color: colors.danger, fontSize: 13, flex: 1 }, active: { minHeight: 74, borderRadius: 8, padding: spacing.md, backgroundColor: colors.primary, flexDirection: "row", alignItems: "center", gap: spacing.md }, activeTitle: { color: colors.surface, fontWeight: "800", fontSize: 16 }, activeMeta: { color: "#DCEDE8", fontSize: 12 },
  metrics: { flexDirection: "row", gap: spacing.sm }, metric: { flex: 1, minHeight: 118 }, metricLabel: { color: colors.muted, fontSize: 12 }, metricValue: { color: colors.text, fontWeight: "800", fontSize: 18 }, cash: { color: colors.danger },
  sync: { minHeight: 50, borderRadius: 6, borderWidth: 1, borderColor: "#B9CCE4", backgroundColor: "#E6EFFA", padding: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm }, syncText: { color: colors.info, fontSize: 13, fontWeight: "700", flex: 1 }, section: { gap: spacing.sm }, offer: { borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: spacing.md, gap: spacing.sm }, route: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, routeLabel: { color: colors.muted, fontSize: 10, fontWeight: "700" }, routeValue: { color: colors.text, fontWeight: "700", fontSize: 14 }, earning: { color: colors.primary, fontSize: 16, fontWeight: "800" }, cashRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, cashText: { color: colors.danger, fontSize: 12, fontWeight: "700" }, pressed: { opacity: 0.68 },
});
